### PR TITLE
Add missing commas to users.csv and tests

### PR DESCRIPTION
**Pull request by cthoyt**
This PR adds missing commas to `users.csv` and adds associated tests to make sure that people enter new rows correctly in the future. This is valuable so the file can be navigated on GitHub.

The tests are written in Python, can be run with:

```bash
git clone https://github.com/trutzig89182/Mastodon-Sociologists
cd Mastodon-Sociologists
pip install tox
tox
```

but are also run for all pushes and PRs via GitHub actions because of the new `tests.yml` file

### CODE REVIEW

**Comment by trutzig89182** [comment]
Hey, thanks! I have one question. Right now the app is not very strict with what it takes. Any user.csv with "account" and "name" somewhere in the header will do. There are many forks out there, who have made their own user.csv, perhaps even with other columns added. I tried to keep my changes it as compatible as possible. Wouldn’t requiring a "well formatted" csv file potentially cause a problem here?

**Comment by cthoyt** [comment]
Yes that's totally possible. In 8235d9d, I changed the testing code to infer the number of columns from the header (which I think we can safely assume will be correctly formatted).

**Comment by trutzig89182** [comment]
Thanks a lot. Could you redirect the pull request to the dev branch? That would be very nice!

**Comment by cthoyt** [comment]
> Thanks a lot. Could you redirect the pull request to the dev branch? That would be very nice!

@trutzig89182 done

**Comment by trutzig89182** [comment]
Great. Thanks a lot for the contribution. It is merged into main my now.

**Pull request merged**
